const PaymentBartAPI = [
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
  {
    image: "images/Comminity/bar.png",
    name: "ABC Establishment",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    BarPrice: "$678",
    PaymentDetail: "View Payment Details",
  },
 
  
];
export default PaymentBartAPI;
