const Modal1API = [
  {
    image: "images/Comminity/user1.png",
    name: "Jane Doe",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    image3: "images/Comminity/users.png",
    BartendarQuantity: 500,
    image4: "images/Comminity/building.png",
    buildingQuantity: 19,
    image5: "images/Comminity/solarStar.png",
    starQuantity: 23,
  },
  {
    image: "images/Comminity/user2.png",
    name: "Jane Doe",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    image3: "images/Comminity/users.png",
    BartendarQuantity: 500,
    image4: "images/Comminity/building.png",
    buildingQuantity: 19,
    image5: "images/Comminity/solarStar.png",
    starQuantity: 23,
  },
  {
    image: "images/Comminity/user3.png",
    name: "Jane Doe",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    image3: "images/Comminity/users.png",
    BartendarQuantity: 500,
    image4: "images/Comminity/building.png",
    buildingQuantity: 19,
    image5: "images/Comminity/solarStar.png",
    starQuantity: 23,
  },
  {
    image: "images/Comminity/user1.png",
    name: "Jane Doe",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    image3: "images/Comminity/users.png",
    BartendarQuantity: 500,
    image4: "images/Comminity/building.png",
    buildingQuantity: 19,
    image5: "images/Comminity/solarStar.png",
    starQuantity: 23,
  },
  {
    image: "images/Comminity/user4.png",
    name: "Jane Doe",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    image3: "images/Comminity/users.png",
    BartendarQuantity: 500,
    image4: "images/Comminity/building.png",
    buildingQuantity: 19,
    image5: "images/Comminity/solarStar.png",
    starQuantity: 23,
  },
  {
    image: "images/Comminity/user5.png",
    name: "Jane Doe",
    image2: "images/Comminity/location.png",
    location: "Charlotte",
    distance: "0.2 mi",
    image3: "images/Comminity/users.png",
    BartendarQuantity: 500,
    image4: "images/Comminity/building.png",
    buildingQuantity: 19,
    image5: "images/Comminity/solarStar.png",
    starQuantity: 23,
  },
];
export default Modal1API;
