const NearbyEstAPI = [
    {
      image: "images/Comminity/bar.png",
      name: "ABC Establishment",
      image2: "images/Comminity/location.png",
      location: "Charlotte",
      distance: "0.2 mi",
      user:"Hired",
      image3: "images/Comminity/users.png",
      BartendarQuantity: 500,
      user1:"bartenders",
      image4: "images/Comminity/solarStar.png",
      starQuantity: 23,
      user2:"reviews",
      user3:"Previously worked",
      image5: "images/Comminity/user1.png",
      image6: "images/Comminity/user2.png",
      image7: "images/Comminity/user5.png",

    },
    {
        image: "images/Comminity/bar.png",
        name: "ABC Establishment",
        image2: "images/Comminity/location.png",
        location: "Charlotte",
        distance: "0.2 mi",
        user:"Hired",
        image3: "images/Comminity/users.png",
        BartendarQuantity: 500,
        user1:"bartenders",
        image4: "images/Comminity/solarStar.png",
        starQuantity: 23,
        user2:"reviews",
        user3:"Previously worked",
        image5: "images/Comminity/user1.png",
        image6: "images/Comminity/user2.png",
        image7: "images/Comminity/user5.png",
  
      },
      {
        image: "images/Comminity/bar.png",
        name: "ABC Establishment",
        image2: "images/Comminity/location.png",
        location: "Charlotte",
        distance: "0.2 mi",
        user:"Hired",
        image3: "images/Comminity/users.png",
        BartendarQuantity: 500,
        user1:"bartenders",
        image4: "images/Comminity/solarStar.png",
        starQuantity: 23,
        user2:"reviews",
        user3:"Previously worked",
        image5: "images/Comminity/user1.png",
        image6: "images/Comminity/user2.png",
        image7: "images/Comminity/user5.png",
  
      },
      {
        image: "images/Comminity/bar.png",
        name: "ABC Establishment",
        image2: "images/Comminity/location.png",
        location: "Charlotte",
        distance: "0.2 mi",
        user:"Hired",
        image3: "images/Comminity/users.png",
        BartendarQuantity: 500,
        user1:"bartenders",
        image4: "images/Comminity/solarStar.png",
        starQuantity: 23,
        user2:"reviews",
        user3:"Previously worked",
        image5: "images/Comminity/user1.png",
        image6: "images/Comminity/user2.png",
        image7: "images/Comminity/user5.png",
  
      },
      {
        image: "images/Comminity/bar.png",
        name: "ABC Establishment",
        image2: "images/Comminity/location.png",
        location: "Charlotte",
        distance: "0.2 mi",
        user:"Hired",
        image3: "images/Comminity/users.png",
        BartendarQuantity: 500,
        user1:"bartenders",
        image4: "images/Comminity/solarStar.png",
        starQuantity: 23,
        user2:"reviews",
        user3:"Previously worked",
        image5: "images/Comminity/user1.png",
        image6: "images/Comminity/user2.png",
        image7: "images/Comminity/user5.png",
  
      },
      {
        image: "images/Comminity/bar.png",
        name: "ABC Establishment",
        image2: "images/Comminity/location.png",
        location: "Charlotte",
        distance: "0.2 mi",
        user:"Hired",
        image3: "images/Comminity/users.png",
        BartendarQuantity: 500,
        user1:"bartenders",
        image4: "images/Comminity/solarStar.png",
        starQuantity: 23,
        user2:"reviews",
        user3:"Previously worked",
        image5: "images/Comminity/user1.png",
        image6: "images/Comminity/user2.png",
        image7: "images/Comminity/user5.png",
  
      },
      {
        image: "images/Comminity/bar.png",
        name: "ABC Establishment",
        image2: "images/Comminity/location.png",
        location: "Charlotte",
        distance: "0.2 mi",
        user:"Hired",
        image3: "images/Comminity/users.png",
        BartendarQuantity: 500,
        user1:"bartenders",
        image4: "images/Comminity/solarStar.png",
        starQuantity: 23,
        user2:"reviews",
        user3:"Previously worked",
        image5: "images/Comminity/user1.png",
        image6: "images/Comminity/user2.png",
        image7: "images/Comminity/user5.png",
  
      },
  ];
  export default NearbyEstAPI;
  